package com.android.server.am;

import com.android.server.backup.BackupManagerConstants;

public class ActivityManagerDebugConfig {
    public static boolean DEBUG_ADD_REMOVE = false;
    public static boolean DEBUG_ALL_ACTIVITIES = false;
    public static boolean DEBUG_ANR = false;
    public static boolean DEBUG_APP = false;
    public static boolean DEBUG_BACKGROUND_CHECK = false;
    public static boolean DEBUG_BACKUP = false;
    public static boolean DEBUG_BROADCAST = false;
    public static boolean DEBUG_BROADCAST_BACKGROUND = false;
    public static boolean DEBUG_BROADCAST_LIGHT = false;
    public static boolean DEBUG_CLEANUP = false;
    public static boolean DEBUG_CONFIGURATION = false;
    public static boolean DEBUG_CONTAINERS = false;
    public static boolean DEBUG_FOCUS = false;
    public static boolean DEBUG_FOREGROUND_SERVICE = false;
    public static boolean DEBUG_IDLE = false;
    public static boolean DEBUG_IMMERSIVE = false;
    public static boolean DEBUG_LOCKTASK = false;
    public static boolean DEBUG_LRU = false;
    public static boolean DEBUG_METRICS = false;
    public static boolean DEBUG_MU = false;
    public static boolean DEBUG_NETWORK = false;
    public static boolean DEBUG_OOM_ADJ = false;
    public static boolean DEBUG_OOM_ADJ_REASON = false;
    public static boolean DEBUG_PAUSE = false;
    public static boolean DEBUG_PERMISSIONS_REVIEW = false;
    public static boolean DEBUG_POWER = false;
    public static boolean DEBUG_POWER_QUICK = false;
    public static boolean DEBUG_PROCESSES = false;
    public static boolean DEBUG_PROCESS_OBSERVERS = false;
    public static boolean DEBUG_PROVIDER = false;
    public static boolean DEBUG_PSS = false;
    public static boolean DEBUG_RECENTS = false;
    public static boolean DEBUG_RECENTS_TRIM_TASKS = false;
    public static boolean DEBUG_RELEASE = false;
    public static boolean DEBUG_RESULTS = false;
    public static boolean DEBUG_SAVED_STATE = false;
    public static boolean DEBUG_SERVICE = false;
    public static boolean DEBUG_SERVICE_EXECUTING = false;
    public static boolean DEBUG_STACK = false;
    public static boolean DEBUG_STATES = false;
    public static boolean DEBUG_SWITCH = false;
    public static boolean DEBUG_TASKS = false;
    public static boolean DEBUG_TRANSITION = false;
    public static boolean DEBUG_UID_OBSERVERS = false;
    public static boolean DEBUG_URI_PERMISSION = false;
    public static boolean DEBUG_USAGE_STATS = false;
    public static boolean DEBUG_USER_LEAVING = false;
    public static boolean DEBUG_VISIBILITY = false;
    public static boolean DEBUG_WHITELISTS = false;
    static final String POSTFIX_ADD_REMOVE;
    static final String POSTFIX_APP;
    static final String POSTFIX_BACKUP;
    static final String POSTFIX_BROADCAST;
    static final String POSTFIX_CLEANUP;
    static final String POSTFIX_CONFIGURATION;
    static final String POSTFIX_CONTAINERS;
    static final String POSTFIX_FOCUS;
    static final String POSTFIX_IDLE;
    static final String POSTFIX_IMMERSIVE;
    static final String POSTFIX_LOCKTASK;
    static final String POSTFIX_LRU;
    static final String POSTFIX_MU = "_MU";
    static final String POSTFIX_NETWORK = "_Network";
    static final String POSTFIX_OOM_ADJ;
    static final String POSTFIX_PAUSE;
    static final String POSTFIX_POWER;
    static final String POSTFIX_PROCESSES;
    static final String POSTFIX_PROCESS_OBSERVERS;
    static final String POSTFIX_PROVIDER;
    static final String POSTFIX_PSS;
    static final String POSTFIX_RECENTS;
    static final String POSTFIX_RELEASE;
    static final String POSTFIX_RESULTS;
    static final String POSTFIX_SAVED_STATE;
    static final String POSTFIX_SERVICE;
    static final String POSTFIX_SERVICE_EXECUTING;
    static final String POSTFIX_STACK;
    static final String POSTFIX_STATES;
    static final String POSTFIX_SWITCH;
    static final String POSTFIX_TASKS;
    static final String POSTFIX_TRANSITION;
    static final String POSTFIX_UID_OBSERVERS;
    static final String POSTFIX_URI_PERMISSION;
    static final String POSTFIX_USER_LEAVING;
    static final String POSTFIX_VISIBILITY;
    static final String TAG_AM = "ActivityManager";
    static final boolean TAG_WITH_CLASS_NAME = false;
    public static boolean APPEND_CATEGORY_NAME = false;
    public static boolean DEBUG_ALL = false;

    static {
        DEBUG_ALL_ACTIVITIES = DEBUG_ALL;
        DEBUG_ADD_REMOVE = DEBUG_ALL_ACTIVITIES;
        DEBUG_ANR = false;
        DEBUG_APP = DEBUG_ALL_ACTIVITIES;
        DEBUG_BACKGROUND_CHECK = DEBUG_ALL;
        DEBUG_BACKUP = DEBUG_ALL;
        DEBUG_BROADCAST = DEBUG_ALL;
        DEBUG_BROADCAST_BACKGROUND = DEBUG_BROADCAST;
        DEBUG_BROADCAST_LIGHT = DEBUG_BROADCAST;
        DEBUG_CLEANUP = DEBUG_ALL;
        DEBUG_CONFIGURATION = DEBUG_ALL;
        DEBUG_CONTAINERS = DEBUG_ALL_ACTIVITIES;
        DEBUG_FOCUS = false;
        DEBUG_IDLE = DEBUG_ALL_ACTIVITIES;
        DEBUG_IMMERSIVE = DEBUG_ALL;
        DEBUG_LOCKTASK = DEBUG_ALL;
        DEBUG_LRU = DEBUG_ALL;
        DEBUG_MU = DEBUG_ALL;
        DEBUG_NETWORK = DEBUG_ALL;
        DEBUG_OOM_ADJ = DEBUG_ALL;
        DEBUG_OOM_ADJ_REASON = DEBUG_ALL;
        DEBUG_PAUSE = DEBUG_ALL;
        DEBUG_POWER = DEBUG_ALL;
        DEBUG_POWER_QUICK = DEBUG_POWER;
        DEBUG_PROCESS_OBSERVERS = DEBUG_ALL;
        DEBUG_PROCESSES = DEBUG_ALL;
        DEBUG_PROVIDER = DEBUG_ALL;
        DEBUG_PSS = DEBUG_ALL;
        DEBUG_RECENTS = DEBUG_ALL;
        DEBUG_RECENTS_TRIM_TASKS = DEBUG_RECENTS;
        DEBUG_RELEASE = DEBUG_ALL_ACTIVITIES;
        DEBUG_RESULTS = DEBUG_ALL;
        DEBUG_SAVED_STATE = DEBUG_ALL_ACTIVITIES;
        DEBUG_SERVICE = DEBUG_ALL;
        DEBUG_FOREGROUND_SERVICE = DEBUG_ALL;
        DEBUG_SERVICE_EXECUTING = DEBUG_ALL;
        DEBUG_STACK = DEBUG_ALL;
        DEBUG_STATES = DEBUG_ALL_ACTIVITIES;
        DEBUG_SWITCH = DEBUG_ALL;
        DEBUG_TASKS = DEBUG_ALL;
        DEBUG_TRANSITION = DEBUG_ALL;
        DEBUG_UID_OBSERVERS = DEBUG_ALL;
        DEBUG_URI_PERMISSION = DEBUG_ALL;
        DEBUG_USER_LEAVING = DEBUG_ALL;
        DEBUG_VISIBILITY = DEBUG_ALL;
        DEBUG_USAGE_STATS = DEBUG_ALL;
        DEBUG_PERMISSIONS_REVIEW = DEBUG_ALL;
        DEBUG_WHITELISTS = DEBUG_ALL;
        DEBUG_METRICS = DEBUG_ALL;
        POSTFIX_ADD_REMOVE = APPEND_CATEGORY_NAME ? "_AddRemove" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_APP = APPEND_CATEGORY_NAME ? "_App" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_BACKUP = APPEND_CATEGORY_NAME ? "_Backup" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_BROADCAST = APPEND_CATEGORY_NAME ? "_Broadcast" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_CLEANUP = APPEND_CATEGORY_NAME ? "_Cleanup" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_CONFIGURATION = APPEND_CATEGORY_NAME ? "_Configuration" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_CONTAINERS = APPEND_CATEGORY_NAME ? "_Containers" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_FOCUS = APPEND_CATEGORY_NAME ? "_Focus" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_IDLE = APPEND_CATEGORY_NAME ? "_Idle" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_IMMERSIVE = APPEND_CATEGORY_NAME ? "_Immersive" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_LOCKTASK = APPEND_CATEGORY_NAME ? "_LockTask" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_LRU = APPEND_CATEGORY_NAME ? "_LRU" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_OOM_ADJ = APPEND_CATEGORY_NAME ? "_OomAdj" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_PAUSE = APPEND_CATEGORY_NAME ? "_Pause" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_POWER = APPEND_CATEGORY_NAME ? "_Power" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_PROCESS_OBSERVERS = APPEND_CATEGORY_NAME ? "_ProcessObservers" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_PROCESSES = APPEND_CATEGORY_NAME ? "_Processes" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_PROVIDER = APPEND_CATEGORY_NAME ? "_Provider" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_PSS = APPEND_CATEGORY_NAME ? "_Pss" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_RECENTS = APPEND_CATEGORY_NAME ? "_Recents" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_RELEASE = APPEND_CATEGORY_NAME ? "_Release" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_RESULTS = APPEND_CATEGORY_NAME ? "_Results" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_SAVED_STATE = APPEND_CATEGORY_NAME ? "_SavedState" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_SERVICE = APPEND_CATEGORY_NAME ? "_Service" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_SERVICE_EXECUTING = APPEND_CATEGORY_NAME ? "_ServiceExecuting" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_STACK = APPEND_CATEGORY_NAME ? "_Stack" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_STATES = APPEND_CATEGORY_NAME ? "_States" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_SWITCH = APPEND_CATEGORY_NAME ? "_Switch" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_TASKS = APPEND_CATEGORY_NAME ? "_Tasks" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_TRANSITION = APPEND_CATEGORY_NAME ? "_Transition" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_UID_OBSERVERS = APPEND_CATEGORY_NAME ? "_UidObservers" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_URI_PERMISSION = APPEND_CATEGORY_NAME ? "_UriPermission" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_USER_LEAVING = APPEND_CATEGORY_NAME ? "_UserLeaving" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
        POSTFIX_VISIBILITY = APPEND_CATEGORY_NAME ? "_Visibility" : BackupManagerConstants.DEFAULT_BACKUP_FINISHED_NOTIFICATION_RECEIVERS;
    }
}
