package mediatek.telephony;

import android.os.PersistableBundle;

public class MtkCarrierConfigManager {
    public static final String KEY_CARRIER_AVOID_CMAS_LIST_BOOL = "carrier_avoid_cmas_list_bool";
    public static final String KEY_CARRIER_INTERNATIONAL_ROAMING_EXCEPTION_LIST_STRINGS = "carrier_international_roaming_exception_list_strings";
    public static final String KEY_DOMESTIC_ROAMING_ENABLED_ONLY_BY_MOBILE_DATA_SETTING = "mtk_domestic_roaming_enabled_only_by_mobile_data_setting";
    public static final String KEY_DOMESTIC_ROAMING_ENABLED_ONLY_BY_MOBILE_DATA_SETTING_CHECK_NW_PLMN = "mtk_domestic_roaming_enabled_only_by_mobile_data_setting_check_nw_plmn";
    public static final String KEY_EMERGENCY_BEARER_MANAGEMENT_POLICY = "emergency_bearer_management_policy";
    public static final String KEY_IMS_PDN_SYNC_FAIL_CAUSE_TO_MODEM_BOOL = "ims_pdn_sync_fail_cause_to_modem_bool";
    public static final String KEY_INTL_ROAMING_ENABLED_ONLY_BY_ROAMING_DATA_SETTING = "mtk_intl_roaming_enabled_only_by_roaming_data_setting";
    public static final String KEY_OPERATOR_ID_INT = "operator_id";
    public static final String KEY_UNIQUE_SETTINGS_FOR_DOMESTIC_AND_INTL_ROAMING = "mtk_unique_settings_for_domestic_and_intl_roaming";
    private static final String LOG_TAG = "MtkCarrierConfigMgr";
    public static final String MTK_KEY_ADD_MNOAPNS_INTO_ALLAPNLIST = "mtk_key_add_mnoapns_into_allapnlist";
    public static final String MTK_KEY_ALLOW_AUTO_START_TIMER_FOR_CANCEL_UPGRADE_BOOL = "mtk_allow_auto_start_timer_for_cancel_upgrade_bool";
    public static final String MTK_KEY_ALLOW_CANCEL_VIDEO_UPGRADE_BOOL = "mtk_allow_cancel_video_upgrade_bool";
    public static final String MTK_KEY_ALLOW_ONE_VIDEO_CALL_ONLY_BOOL = "mtk_allow_one_video_call_only_bool";
    public static final String MTK_KEY_ALLOW_ONE_WAY_VIDEO_BOOL = "mtk_allow_one_way_video_bool";
    public static final String MTK_KEY_BLIND_ASSURED_ECT_SUPPORTED = "mtk_carrier_blind_assured_ect_supported";
    public static final String MTK_KEY_CARRIER_IMS_ECBM_SUPPORTED = "mtk_carrier_ims_ecbm_supported";
    public static final String MTK_KEY_CARRIER_NEED_SHOW_ROAMING_ICON = "mtk_key_carrier_need_show_roaming_icon";
    public static final String MTK_KEY_CARRIER_NOTIFY_BAD_WIFI_QUALITY_DISCONNECT_CAUSE = "mtk_carrier_notify_bad_wifi_quality_disconnect_cause";
    public static final String MTK_KEY_CARRIER_NOURTH_AMERICA_HIGH_PRIORITY_CLIR_PREFIX_SUPPORTED = "mtk_carrier_nouth_america_high_priority_clir_prefix_supported";
    public static final String MTK_KEY_CARRIER_SS_ENABLE_XCAP_HTTP_RESPONSE_409 = "mtk_carrier_ss_enable_xcap_http_response_409";
    public static final String MTK_KEY_CARRIER_SS_GSM_UT_SUPPORT = "mtk_carrier_ss_gsm_ut_support";
    public static final String MTK_KEY_CARRIER_SS_IMS_NW_CW = "mtk_carrier_ss_ims_nw_cw";
    public static final String MTK_KEY_CARRIER_SS_NEED_CHECK_DATA_ENABLE = "mtk_carrier_ss_need_check_data_enable";
    public static final String MTK_KEY_CARRIER_SS_NEED_CHECK_DATA_ROAMING = "mtk_carrier_ss_need_check_data_roaming";
    public static final String MTK_KEY_CARRIER_SS_NOT_SUPPORT_CALL_IDENTITY = "mtk_carrier_ss_not_support_call_identity";
    public static final String MTK_KEY_CARRIER_SS_NOT_SUPPORT_OCB = "mtk_carrier_ss_not_support_ocb";
    public static final String MTK_KEY_CARRIER_SS_NOT_SUPPORT_WFC_UT = "mtk_carrier_ss_not_support_wfc_ut";
    public static final String MTK_KEY_CARRIER_SS_NOT_SUPPORT_XCAP = "mtk_carrier_ss_not_support_xcap";
    public static final String MTK_KEY_CARRIER_SS_QUERY_CFU_AGAIN_AFTER_SET = "mtk_carrier_ss_query_cfu_again_after_set";
    public static final String MTK_KEY_CARRIER_SS_RE_REGISTER_FOR_CF = "mtk_carrier_ss_re_register_for_cf";
    public static final String MTK_KEY_CARRIER_SS_SUPPORT_SAVE_CF_NUMBER = "mtk_carrier_ss_support_save_cf_number";
    public static final String MTK_KEY_CARRIER_SS_TB_CLIR = "mtk_carrier_ss_tb_clir";
    public static final String MTK_KEY_CARRIER_SS_TRANSFER_XCAP_404 = "mtk_carrier_ss_transfer_xcap_404";
    public static final String MTK_KEY_CARRIER_SWAP_CONFERENCE_TO_FOREGROUND_BEFORE_MERGE = "mtk_carrier_swap_conference_to_foreground_before_merge";
    public static final String MTK_KEY_CARRIER_SWAP_VT_CONFERENCE_TO_FOREGROUND_BEFORE_MERGE = "mtk_carrier_swap_vt_conference_to_foreground_before_merge";
    public static final String MTK_KEY_CARRIER_SWITCH_WFC_MODE_REQUIRED_BOOL = "mtk_carrier_switch_wfc_mode_required_bool";
    public static final String MTK_KEY_CARRIER_TURN_OFF_WIFI_BEFORE_E911 = "mtk_carrier_turn_off_wifi_before_e911";
    public static final String MTK_KEY_CARRIER_UPDATE_DIALING_ADDRESS_FROM_PAU = "mtk_carrier_update_dialing_address_from_pau";
    public static final String MTK_KEY_CDMA_SMS_7_BIT_ENCODING_TYPE_INT = "mtk_cdma_sms_7bit_encoding_type_int";
    public static final String MTK_KEY_CONFERENCE_MANAGEMENT_SUPPORTED = "mtk_key_conference_management_supported";
    public static final String MTK_KEY_CONF_FIRST_PARTICIPANT_AS_HOST_SUPPORTED = "mtk_key_conference_first_participant_as_host_supported";
    public static final String MTK_KEY_CONSULTATIVE_ECT_SUPPORTED = "mtk_carrier_consultative_ect_supported";
    public static final String MTK_KEY_CT_VOLTE_STATUS_BOOL = "mtk_ct_volte_status_bool";
    public static final String MTK_KEY_DEFAULT_DNS_ENABLED_BOOL = "default_dns_enabled_bool";
    public static final String MTK_KEY_DEFAULT_ENHANCED_4G_MODE_BOOL = "mtk_default_enhanced_4g_mode_bool";
    public static final String MTK_KEY_DEFAULT_WFC_MODE_INT = "mtk_default_wfc_mode_int";
    public static final String MTK_KEY_DEVICE_SWITCH_SUPPORTED = "mtk_carrier_device_switch_supported";
    public static final String MTK_KEY_DIALER_CALL_PULL_BOOL = "mtk_dialer_call_pull_bool";
    public static final String MTK_KEY_DISABLE_VT_OVER_WIFI_BOOL = "disable_vt_over_wifi_bool";
    public static final String MTK_KEY_DISCONNECT_ALL_CALLS_WHEN_ECC_BOOL = "mtk_key_disconnect_all_calls_when_ecc_bool";
    public static final String MTK_KEY_EMS_WAITING_MISSING_SEGMENT_TIME_INT = "mtk_ems_waiting_missing_segment_time";
    public static final String MTK_KEY_IGNORE_DATA_ROAMING_FOR_VIDEO_CALLS = "mtk_ignore_data_roaming_for_video_calls";
    public static final String MTK_KEY_IMS_NO_CONF_REQ_AFTER_MAX_CONNECTION_BOOL = "no_merge_req_after_max_connection";
    public static final String MTK_KEY_IMS_NO_SIP_MESSAGE_ON_PAUSE_VIDEO_BOOL = "no_sip_message_on_pause_video_bool";
    public static final String MTK_KEY_IMS_SUPPORT_AUTO_DECLINE_UPGRADE_REQUEST_BOOL = "support_auto_decline_upgrade_request_bool";
    public static final String MTK_KEY_MULTILINE_ALLOW_CROSS_LINE_CONFERENCE_BOOL = "mtk_key_multiline_allow_cross_line_conference_bool";
    public static final String MTK_KEY_OPERATE_IMS_CONFERENCE_PARTICIPANTS_BY_USER_ENTITY = "mtk_key_operate_ims_conference_participants_by_user_entity";
    public static final String MTK_KEY_RESTORE_ADDRESS_FOR_IMS_CONFERENCE_PARTICIPANTS = "mtk_key_restore_address_for_ims_conference_participants";
    public static final String MTK_KEY_RESUME_HOLD_CALL_AFTER_ACTIVE_CALL_END_BY_REMOTE = "mtk_resume_hold_call_after_active_call_end_by_remote";
    public static final String MTK_KEY_ROAMING_BAR_GUARD_BOOL = "mtk_key_roaming_bar_guard_bool";
    public static final String MTK_KEY_RTT_ADVANCED_FEATURES_SUPPORT_BOOL = "mtk_rtt_advanced_features_support_bool";
    public static final String MTK_KEY_SHOW_CALL_BARRING_PASSWORD_BOOL = "mtk_show_call_barring_password_bool";
    public static final String MTK_KEY_SHOW_CLIR_SETTING_BOOL = "mtk_show_clir_setting_bool";
    public static final String MTK_KEY_SHOW_OPEN_MOBILE_DATA_DIALOG_BOOL = "mtk_show_open_mobile_data_dialog_bool";
    public static final String MTK_KEY_SHOW_TOAST_WHEN_CONFERENCE_FULL_BOOL = "show_toast_when_conference_full";
    public static final String MTK_KEY_SUPPORT_VT_SS_BOOL = "mtk_support_vt_ss_bool";
    public static final String MTK_KEY_TIMER_FOR_CANCEL_UPGRADE_INT = "mtk_timer_for_cancel_upgrade_int";
    public static final String MTK_KEY_TIMER_FOR_DECLINE_UPGRADE_INT = "mtk_timer_for_decline_upgrade_int";
    public static final String MTK_KEY_UPDATE_WIFICALLING_BY_TTY = "mtk_key_update_wificalling_by_tty";
    public static final String MTK_KEY_USE_ADMINISTRATIVE_APN_BOOL = "mtk_use_administrative_apn_bool";
    public static final String MTK_KEY_VIDEO_CALL_BACKGROUND_TRANSMISSION = "mtk_video_call_background_transmission";
    public static final String MTK_KEY_VOLTE_CONFERENCE_ENHANCED_ENABLE_BOOL = "mtk_volte_conference_enhanced_enable_bool";
    public static final String MTK_KEY_VT_DIALPAD_SUPPORT_BOOL = "mtk_vt_dialpad_support_bool";
    public static final String MTK_KEY_WFC_PROV_SUPPORTED_BOOL = "mtk_wfc_provisioning_supported_bool";
    public static final String MTK_KEY_WFC_REMOVE_PREFERENCE_MODE_BOOL = "mtk_wfc_remove_preference_mode_bool";
    public static final String MTK_KEY_WFC_SETTINGS_UX_TYPE_INT = "mtk_wfc_settings_ux_type_int";
    public static final String MTK_KEY_WOS_SUPPORT_WFC_IN_FLIGHTMODE = "wos_flight_mode_support_bool";

    public static void putDefault(PersistableBundle persistableBundle) {
        persistableBundle.putBoolean("carrier_volte_available_bool", true);
        persistableBundle.putBoolean("carrier_vt_available_bool", true);
        persistableBundle.putBoolean("carrier_wfc_ims_available_bool", true);
        persistableBundle.putBoolean(MTK_KEY_VOLTE_CONFERENCE_ENHANCED_ENABLE_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_ALLOW_ONE_VIDEO_CALL_ONLY_BOOL, false);
        persistableBundle.putStringArray(KEY_CARRIER_INTERNATIONAL_ROAMING_EXCEPTION_LIST_STRINGS, new String[]{""});
        persistableBundle.putInt(MTK_KEY_CDMA_SMS_7_BIT_ENCODING_TYPE_INT, 9);
        persistableBundle.putInt(MTK_KEY_EMS_WAITING_MISSING_SEGMENT_TIME_INT, 60);
        persistableBundle.putBoolean(MTK_KEY_DEFAULT_ENHANCED_4G_MODE_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_USE_ADMINISTRATIVE_APN_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_WFC_REMOVE_PREFERENCE_MODE_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_SHOW_CLIR_SETTING_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_SHOW_OPEN_MOBILE_DATA_DIALOG_BOOL, false);
        persistableBundle.putInt(MTK_KEY_WFC_SETTINGS_UX_TYPE_INT, -1);
        persistableBundle.putInt(MTK_KEY_DEFAULT_WFC_MODE_INT, 2);
        persistableBundle.putBoolean(MTK_KEY_WFC_PROV_SUPPORTED_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_SUPPORT_VT_SS_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_DIALER_CALL_PULL_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_ALLOW_ONE_WAY_VIDEO_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_ALLOW_CANCEL_VIDEO_UPGRADE_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_ALLOW_AUTO_START_TIMER_FOR_CANCEL_UPGRADE_BOOL, false);
        persistableBundle.putInt(MTK_KEY_TIMER_FOR_CANCEL_UPGRADE_INT, 20);
        persistableBundle.putInt(MTK_KEY_TIMER_FOR_DECLINE_UPGRADE_INT, 20);
        persistableBundle.putBoolean("support_pause_ims_video_calls_bool", true);
        persistableBundle.putBoolean("ignore_data_enabled_changed_for_video_calls", false);
        persistableBundle.putBoolean(KEY_IMS_PDN_SYNC_FAIL_CAUSE_TO_MODEM_BOOL, false);
        persistableBundle.putInt(KEY_OPERATOR_ID_INT, 0);
        persistableBundle.putBoolean(KEY_DOMESTIC_ROAMING_ENABLED_ONLY_BY_MOBILE_DATA_SETTING, false);
        persistableBundle.putStringArray(KEY_DOMESTIC_ROAMING_ENABLED_ONLY_BY_MOBILE_DATA_SETTING_CHECK_NW_PLMN, null);
        persistableBundle.putBoolean(KEY_INTL_ROAMING_ENABLED_ONLY_BY_ROAMING_DATA_SETTING, false);
        persistableBundle.putBoolean(KEY_UNIQUE_SETTINGS_FOR_DOMESTIC_AND_INTL_ROAMING, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_GSM_UT_SUPPORT, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_NOT_SUPPORT_XCAP, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_TB_CLIR, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_IMS_NW_CW, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_ENABLE_XCAP_HTTP_RESPONSE_409, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_TRANSFER_XCAP_404, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_NOT_SUPPORT_CALL_IDENTITY, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_RE_REGISTER_FOR_CF, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_SUPPORT_SAVE_CF_NUMBER, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_QUERY_CFU_AGAIN_AFTER_SET, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_NOT_SUPPORT_OCB, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_NOT_SUPPORT_WFC_UT, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_NEED_CHECK_DATA_ENABLE, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SS_NEED_CHECK_DATA_ROAMING, false);
        persistableBundle.putStringArray(KEY_EMERGENCY_BEARER_MANAGEMENT_POLICY, new String[]{""});
        persistableBundle.putBoolean(MTK_KEY_CT_VOLTE_STATUS_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_ROAMING_BAR_GUARD_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_NOURTH_AMERICA_HIGH_PRIORITY_CLIR_PREFIX_SUPPORTED, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SWAP_CONFERENCE_TO_FOREGROUND_BEFORE_MERGE, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_UPDATE_DIALING_ADDRESS_FROM_PAU, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_TURN_OFF_WIFI_BEFORE_E911, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_IMS_ECBM_SUPPORTED, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_NOTIFY_BAD_WIFI_QUALITY_DISCONNECT_CAUSE, false);
        persistableBundle.putBoolean(MTK_KEY_VIDEO_CALL_BACKGROUND_TRANSMISSION, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SWITCH_WFC_MODE_REQUIRED_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_BLIND_ASSURED_ECT_SUPPORTED, false);
        persistableBundle.putBoolean(MTK_KEY_CONSULTATIVE_ECT_SUPPORTED, true);
        persistableBundle.putBoolean(MTK_KEY_DEVICE_SWITCH_SUPPORTED, false);
        persistableBundle.putBoolean(MTK_KEY_RESTORE_ADDRESS_FOR_IMS_CONFERENCE_PARTICIPANTS, true);
        persistableBundle.putBoolean(MTK_KEY_OPERATE_IMS_CONFERENCE_PARTICIPANTS_BY_USER_ENTITY, false);
        persistableBundle.putBoolean(MTK_KEY_CONF_FIRST_PARTICIPANT_AS_HOST_SUPPORTED, false);
        persistableBundle.putBoolean(MTK_KEY_DEFAULT_DNS_ENABLED_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_ADD_MNOAPNS_INTO_ALLAPNLIST, false);
        persistableBundle.putBoolean(MTK_KEY_WOS_SUPPORT_WFC_IN_FLIGHTMODE, true);
        persistableBundle.putBoolean(KEY_CARRIER_AVOID_CMAS_LIST_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_SHOW_TOAST_WHEN_CONFERENCE_FULL_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_IMS_NO_CONF_REQ_AFTER_MAX_CONNECTION_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_NEED_SHOW_ROAMING_ICON, true);
        persistableBundle.putBoolean(MTK_KEY_DISABLE_VT_OVER_WIFI_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_SHOW_CALL_BARRING_PASSWORD_BOOL, false);
        persistableBundle.putBoolean("gsm_cdma_calls_can_be_hd_audio", true);
        persistableBundle.putBoolean(MTK_KEY_MULTILINE_ALLOW_CROSS_LINE_CONFERENCE_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_RTT_ADVANCED_FEATURES_SUPPORT_BOOL, false);
        persistableBundle.putBoolean("call_barring_visibility_bool", true);
        persistableBundle.putBoolean(MTK_KEY_IMS_NO_SIP_MESSAGE_ON_PAUSE_VIDEO_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_VT_DIALPAD_SUPPORT_BOOL, false);
        persistableBundle.putBoolean(MTK_KEY_RESUME_HOLD_CALL_AFTER_ACTIVE_CALL_END_BY_REMOTE, false);
        persistableBundle.putBoolean(MTK_KEY_IMS_SUPPORT_AUTO_DECLINE_UPGRADE_REQUEST_BOOL, true);
        persistableBundle.putBoolean(MTK_KEY_UPDATE_WIFICALLING_BY_TTY, false);
        persistableBundle.putBoolean(MTK_KEY_IGNORE_DATA_ROAMING_FOR_VIDEO_CALLS, false);
        persistableBundle.putBoolean(MTK_KEY_CARRIER_SWAP_VT_CONFERENCE_TO_FOREGROUND_BEFORE_MERGE, false);
        persistableBundle.putBoolean(MTK_KEY_DISCONNECT_ALL_CALLS_WHEN_ECC_BOOL, true);
    }
}
