package com.android.server.wifi;

import java.util.Arrays;

public class WifiLinkLayerStats {
    public int beacon_rx;
    public long lostmpdu_be;
    public long lostmpdu_bk;
    public long lostmpdu_vi;
    public long lostmpdu_vo;
    public int on_time;
    public int on_time_scan;
    public long retries_be;
    public long retries_bk;
    public long retries_vi;
    public long retries_vo;
    public int rssi_mgmt;
    public int rx_time;
    public long rxmpdu_be;
    public long rxmpdu_bk;
    public long rxmpdu_vi;
    public long rxmpdu_vo;
    public long timeStampInMs;
    public int tx_time;
    public int[] tx_time_per_level;
    public long txmpdu_be;
    public long txmpdu_bk;
    public long txmpdu_vi;
    public long txmpdu_vo;

    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(" WifiLinkLayerStats: ");
        sb.append('\n');
        sb.append(" my bss beacon rx: ");
        sb.append(Integer.toString(this.beacon_rx));
        sb.append('\n');
        sb.append(" RSSI mgmt: ");
        sb.append(Integer.toString(this.rssi_mgmt));
        sb.append('\n');
        sb.append(" BE : ");
        sb.append(" rx=");
        sb.append(Long.toString(this.rxmpdu_be));
        sb.append(" tx=");
        sb.append(Long.toString(this.txmpdu_be));
        sb.append(" lost=");
        sb.append(Long.toString(this.lostmpdu_be));
        sb.append(" retries=");
        sb.append(Long.toString(this.retries_be));
        sb.append('\n');
        sb.append(" BK : ");
        sb.append(" rx=");
        sb.append(Long.toString(this.rxmpdu_bk));
        sb.append(" tx=");
        sb.append(Long.toString(this.txmpdu_bk));
        sb.append(" lost=");
        sb.append(Long.toString(this.lostmpdu_bk));
        sb.append(" retries=");
        sb.append(Long.toString(this.retries_bk));
        sb.append('\n');
        sb.append(" VI : ");
        sb.append(" rx=");
        sb.append(Long.toString(this.rxmpdu_vi));
        sb.append(" tx=");
        sb.append(Long.toString(this.txmpdu_vi));
        sb.append(" lost=");
        sb.append(Long.toString(this.lostmpdu_vi));
        sb.append(" retries=");
        sb.append(Long.toString(this.retries_vi));
        sb.append('\n');
        sb.append(" VO : ");
        sb.append(" rx=");
        sb.append(Long.toString(this.rxmpdu_vo));
        sb.append(" tx=");
        sb.append(Long.toString(this.txmpdu_vo));
        sb.append(" lost=");
        sb.append(Long.toString(this.lostmpdu_vo));
        sb.append(" retries=");
        sb.append(Long.toString(this.retries_vo));
        sb.append('\n');
        sb.append(" on_time : ");
        sb.append(Integer.toString(this.on_time));
        sb.append(" rx_time=");
        sb.append(Integer.toString(this.rx_time));
        sb.append(" scan_time=");
        sb.append(Integer.toString(this.on_time_scan));
        sb.append('\n');
        sb.append(" tx_time=");
        sb.append(Integer.toString(this.tx_time));
        sb.append(" tx_time_per_level=" + Arrays.toString(this.tx_time_per_level));
        sb.append(" ts=" + this.timeStampInMs);
        return sb.toString();
    }
}
