package com.android.server.wm;

import com.mediatek.server.MtkSystemServiceFactory;
import com.mediatek.server.wm.WindowManagerDebugger;

public class WindowManagerDebugConfig {
    static boolean DEBUG_ANIM = false;
    static boolean DEBUG_APP_ORIENTATION = false;
    static boolean DEBUG_APP_TRANSITIONS = false;
    static boolean DEBUG_BOOT = false;
    static boolean DEBUG_CONFIGURATION = false;
    static boolean DEBUG_DIM_LAYER = false;
    static boolean DEBUG_DISPLAY = false;
    static boolean DEBUG_DRAG = false;
    static boolean DEBUG_FOCUS_LIGHT = false;
    static boolean DEBUG_INPUT = false;
    static boolean DEBUG_INPUT_METHOD = false;
    static boolean DEBUG_KEEP_SCREEN_ON = false;
    static boolean DEBUG_KEYGUARD = false;
    static boolean DEBUG_LAYERS = false;
    public static boolean DEBUG_LAYOUT = false;
    static boolean DEBUG_LAYOUT_REPEATS = false;
    static boolean DEBUG_ORIENTATION = false;
    static boolean DEBUG_POWER = false;
    static final boolean DEBUG_RECENTS_ANIMATIONS = false;
    static final boolean DEBUG_REMOTE_ANIMATIONS;
    static boolean DEBUG_SCREENSHOT = false;
    static boolean DEBUG_SCREEN_ON = false;
    static boolean DEBUG_STACK = false;
    static boolean DEBUG_STARTING_WINDOW = false;
    static boolean DEBUG_STARTING_WINDOW_VERBOSE = false;
    static boolean DEBUG_TASK_MOVEMENT = false;
    static boolean DEBUG_TASK_POSITIONING = false;
    static boolean DEBUG_TOKEN_MOVEMENT = false;
    static boolean DEBUG_UNKNOWN_APP_VISIBILITY = false;
    static boolean DEBUG_VISIBILITY = false;
    static boolean DEBUG_WALLPAPER = false;
    static boolean DEBUG_WALLPAPER_LIGHT = false;
    static boolean DEBUG_WINDOW_CROP = false;
    static boolean DEBUG_WINDOW_MOVEMENT = false;
    static boolean DEBUG_WINDOW_TRACE = false;
    static boolean SHOW_LIGHT_TRANSACTIONS = false;
    static boolean SHOW_STACK_CRAWLS = false;
    static boolean SHOW_SURFACE_ALLOC = false;
    static boolean SHOW_TRANSACTIONS = false;
    static boolean SHOW_VERBOSE_TRANSACTIONS = false;
    static final String TAG_KEEP_SCREEN_ON = "DebugKeepScreenOn";
    static final boolean TAG_WITH_CLASS_NAME = false;
    static final String TAG_WM = "WindowManager";
    private static WindowManagerDebugger mWindowManagerDebugger = MtkSystemServiceFactory.getInstance().makeWindowManagerDebugger();
    static boolean DEBUG_RESIZE = false;
    static boolean DEBUG = false;
    static boolean DEBUG_ADD_REMOVE = false;
    static boolean DEBUG_FOCUS = false;

    static {
        boolean z;
        if (!DEBUG_FOCUS) {
            WindowManagerDebugger windowManagerDebugger = mWindowManagerDebugger;
            z = WindowManagerDebugger.WMS_DEBUG_USER;
        }
        DEBUG_FOCUS_LIGHT = z;
        DEBUG_ANIM = false;
        DEBUG_KEYGUARD = false;
        DEBUG_LAYOUT = false;
        DEBUG_LAYERS = false;
        DEBUG_INPUT = false;
        DEBUG_INPUT_METHOD = false;
        DEBUG_VISIBILITY = false;
        DEBUG_WINDOW_MOVEMENT = false;
        DEBUG_TOKEN_MOVEMENT = false;
        DEBUG_ORIENTATION = false;
        DEBUG_APP_ORIENTATION = false;
        DEBUG_CONFIGURATION = false;
        DEBUG_APP_TRANSITIONS = false;
        DEBUG_STARTING_WINDOW_VERBOSE = false;
        DEBUG_STARTING_WINDOW = DEBUG_STARTING_WINDOW_VERBOSE;
        DEBUG_WALLPAPER = false;
        DEBUG_WALLPAPER_LIGHT = DEBUG_WALLPAPER;
        DEBUG_DRAG = false;
        WindowManagerDebugger windowManagerDebugger2 = mWindowManagerDebugger;
        DEBUG_SCREEN_ON = WindowManagerDebugger.WMS_DEBUG_USER;
        DEBUG_SCREENSHOT = false;
        WindowManagerDebugger windowManagerDebugger3 = mWindowManagerDebugger;
        DEBUG_BOOT = WindowManagerDebugger.WMS_DEBUG_USER;
        DEBUG_LAYOUT_REPEATS = false;
        DEBUG_WINDOW_TRACE = false;
        DEBUG_TASK_MOVEMENT = false;
        DEBUG_TASK_POSITIONING = false;
        DEBUG_STACK = false;
        WindowManagerDebugger windowManagerDebugger4 = mWindowManagerDebugger;
        DEBUG_DISPLAY = WindowManagerDebugger.WMS_DEBUG_USER;
        DEBUG_POWER = false;
        DEBUG_DIM_LAYER = false;
        SHOW_SURFACE_ALLOC = false;
        SHOW_TRANSACTIONS = false;
        SHOW_VERBOSE_TRANSACTIONS = false;
        SHOW_LIGHT_TRANSACTIONS = SHOW_TRANSACTIONS;
        SHOW_STACK_CRAWLS = false;
        DEBUG_WINDOW_CROP = false;
        DEBUG_UNKNOWN_APP_VISIBILITY = false;
        DEBUG_REMOTE_ANIMATIONS = DEBUG_APP_TRANSITIONS;
        DEBUG_KEEP_SCREEN_ON = false;
    }
}
